### ISSUE TITLE
почитал, запустил.

### ISSUE THREAD

**Issue by seg54321** [vantipin/CalamityKingdom-#2]
до сих пор валяюсь под столом вместе с женой :)
кто автор текстов?
Прекрасные тексты и графика. Почему не выкладываете в Appstore? 
я так понимаю MIT позволяет это сделать ээээ кому угодно использовать ваш труд ?
если не сложно, напишите пару слов на qqeeqqww@gmail.com.
искать ваши контакты ... не нашел в общем кроме фоток ваших девушек.

**Comment by vantipin** [comment]
Привет,

Спасибо что обратили внимание на наш проект. Ваше замечение по поводу лицензии имеет смысл. 

Хорошего дня!
Влад

**Comment by seg54321** [comment]
Здравствуйте, Влад
Вы планируете выкладывать этот проект в Аппсторе или он “умер”? 
Или будете искать спонсора?
Или он “для фана” ? 
Предложений то по этому проекту намного больше, вопрос нужны ли они кому нибудь :)
Хочу отметить что тексты для проекта просто огонь!  :) 
собственно они и представляют основной интерес к проекту :)
Удачного дня, Петр

**Comment by vantipin** [comment]
У всех в команде случилась "жизнь" и сейчас нету свободных рук чтобы его допилить. Периодически проект обсуждается и есть желание его доделать и выпустить. Вопрос спонсора пока не обсуждался.

Почему вы говорите что по проекту много предложений?

**Comment by JerkUp** [comment]
Очень хочется его доделать, время от времени хотим собраться, обсудить в каком виде его лучше сделать (изначально игра была без таймера, потом решили сделать с таймером), но все никак не выходит. Да и по-хорошему переписать бы проект, т.к. писался код давно и за один день, грубо говоря, много косяков.

**Comment by GrishaRaikhman** [comment]
Привет, тексты писал я.
Если у вас есть предложения по проекту, свяжитесь со мной в skype (torkvemada87), обсудим.
Проект заморозили до лучших времен из-за проблем с геймплеем, текущая система плохо играется. Предполагается, что это должен быть тайм-менеджер, но сейчас он в этом плане работает так себе.

**Comment by seg54321** [comment]
Добрый день, уважаемые разработчики.
Предложений много, т.к. игра понравилась. Красивая графика, тексты прост огонь. Но нет конца, где то к 8 дню наблюдаю дисбаланс ресурсов (или плохо играю :). Концовки нет, а хотелось бы :) 
насчет тайм-менеджмента - не разобрался :(
Я напишу как соберусь с мыслями .
написали код ЗА ОДИН ДЕНЬ ??? вау. круто.
а какая монетизация планировалась для этого проекта? 
или есть денежная работа и не до него? 
я правильно понимаю что любой может принять участие в проекте, сделать форк или вступить в вашу команду, "внести вклад" так сказать :) ?

**Comment by GrishaRaikhman** [comment]
Я же говорю, свяжитесь со мной в скайпе, обсудим =)

**Comment by seg54321** [comment]
Хочу еще раз поблагодарить Вас за прекрасную идею и зажигательные тексты! 
Код правда пришлось изрядно по-рефакторить, но как вы "пишите за 1 день" правильно и удобно  не напишешь. Тем не менее отзывы в Аппсторе положительные, народ покупает :) 
PS: тексты достойно улучшить/добавить не удалось - тут вся надежда на Вас.
